feat: initial release of 1.0.0

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-# The path to the commitlint binary.
-COMMAND=common/temp/node_modules/.bin/commitlint
+# The commit-msg hook takes one parameter, which is the path to a temporary file that
+# contains the commit message written by the developer. If this script exits non-zero,
+# Git aborts the commit process so can be used to validate the project state or commit
+# message before allowing a commit to go through.
 
-# Determine whether commitlint is installed.
-if [ -f $COMMAND ]; then
-  $COMMAND --edit --extends @commitlint/config-conventional
-else
-  echo Commitlint not installed
-fi
+# Invoke the "rush commitlint" custom command to validate the commit message against
+# conventional spec. The command is defined in common/config/rush/command-line.json
+# and uses the "commitlint" autoinstaller.
+node common/scripts/install-run-rush.js commitlint || exit $?
